from __future__ import annotations

from pathlib import Path


def _save_local_symbol_library(schematic_path: Path, library_symbols: list[str]) -> None:
    """Write the local KiCad symbol library and sym-lib-table beside the schematic."""
    folder = schematic_path.parent
    sym_lib = folder / "GeneratedSymbols.kicad_sym"
    symbol_table = folder / "sym-lib-table"
    lines = [
        "(kicad_symbol_lib",
        "  (version 20211014)",
        '  (generator "schematic_generator")',
    ]
    for line in library_symbols:
        if line.startswith('    (symbol "GeneratedSymbols:'):
            lines.append(line.replace('    (symbol "GeneratedSymbols:', '  (symbol "', 1))
        else:
            lines.append(line[2:] if line.startswith("    ") else line)
    lines.append(")")
    sym_lib.write_text("\n".join(lines) + "\n", encoding="utf-8")
    symbol_table.write_text(
        "\n".join([
            "(sym_lib_table",
            '  (lib (name "GeneratedSymbols") (type "KiCad") '
            '(uri "${KIPRJMOD}/GeneratedSymbols.kicad_sym") (options "") '
            '(descr "Local symbols generated by GeneratedSymbols"))',
            ")",
        ]) + "\n",
        encoding="utf-8",
    )
